-- SQL statements for recipes 101-120

-- Recipe 101: Apple & Lancashire cheese pie
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(101, 'Apple & Lancashire cheese pie', '[{"section_title": "Main", "items": [{"name": "all butter puff pastry", "quantity": "500", "unit": "g"}, {"name": "vegetable stock cube", "quantity": "1"}, {"name": "waxy potatoes", "quantity": "300", "unit": "g"}, {"name": "apples (Royal Gala, Golden Russet, or Cox)", "quantity": "4"}, {"name": "shallots", "quantity": "2"}, {"name": "Lancashire or sharp Cheddar cheese", "quantity": "200-250", "unit": "g"}, {"name": "fresh thyme", "quantity": "2", "unit": "sprigs"}, {"name": "large free-range egg", "quantity": "1"}]}]', '["Preheat the oven to 190°C/375°F/gas 5.", "Cut the pastry into 2 pieces, then roll each into a rectangle slightly larger than A4.", "Fill a saucepan with boiling water and add the stock cube. Cut the potatoes into 5mm discs and boil for 3 to 4 minutes, then drain and allow to steam dry.", "Line a baking tray with greaseproof paper and lay one pastry rectangle on top.", "Arrange half the potatoes in an even layer over the pastry, leaving a 2cm gap around the edges, and season.", "Finely slice the apples into discs, then layer half over the potatoes.", "Peel, finely slice and scatter over half the shallot, grate over half the cheese and pick over half the thyme leaves.", "Repeat with another layer of potatoes, seasoning, apples, shallot, cheese and thyme.", "Beat the egg and brush the edges of the pastry with a little egg, then lay the second pastry rectangle on top, carefully stretching and moulding it over the filling. Press the edges together with your fingers or a fork.", "Score the top of the pie, brush the pastry with egg then bake for about 30 to 40 minutes, or until golden and puffed up.", "Cut the pie into wedges and serve with chutney and salad leaves."]', '["Vegetarian", "Pie"]');

-- Recipe 102: Caribbean Channa
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(102, 'Caribbean Channa', '[{"section_title": "Main", "items": [{"name": "vegetable oil", "quantity": "1", "unit": "tbsp"}, {"name": "onion, finely chopped", "quantity": "1"}, {"name": "cayenne pepper", "quantity": "½-1", "unit": "tsp"}, {"name": "ground turmeric", "quantity": "1", "unit": "tbsp"}, {"name": "paprika", "quantity": "1", "unit": "tbsp"}, {"name": "Madras curry powder", "quantity": "1", "unit": "tbsp"}, {"name": "ground cumin", "quantity": "1", "unit": "tbsp"}, {"name": "garlic cloves, finely chopped", "quantity": "3"}, {"name": "fresh root ginger, peeled and grated", "quantity": "Thumb-sized piece"}, {"name": "medium carrots, peeled and cut into small chunks", "quantity": "2"}, {"name": "medium all-purpose potatoes, peeled and cut into small chunks", "quantity": "2"}, {"name": "tins of chickpeas, drained and rinsed", "quantity": "2x400", "unit": "g"}, {"name": "vegetable stock", "quantity": "500", "unit": "ml"}, {"name": "fresh parsley, roughly chopped", "quantity": "Handful", "notes": "to garnish"}, {"name": "Salt and black pepper", "quantity": "to taste"}]}]', '["Pour the vegetable oil into a large saucepan, add the onion and sauté over a medium heat for 5-6 minutes until softened and lightly browned.", "Add the spices and some salt and pepper, followed by the garlic and ginger, and cook for another 5 minutes until the garlic has softened.", "Tip the carrots, potatoes and chickpeas into the pan and mix well to coat in the spiced onion mixture.", "Pour in the stock and stir everything together well, then cover the pan with a lid and bring to the boil.", "Reduce the heat and cook for about 30 minutes until the potatoes and carrots are tender, then remove the lid and simmer for another few minutes until thickened.", "Taste and add more salt and pepper if needed.", "Once cooked, remove from the heat and garnish with the chopped parsley. Serve with rotis, fried plantains and red cabbage slaw."]', '["Vegetarian", "Vegan", "Curry"]');

-- Recipe 103: Summer vegetable pilaf
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(103, 'Summer vegetable pilaf', '[{"section_title": "Main", "items": [{"name": "olive oil", "quantity": "2.5", "unit": "tbsp"}, {"name": "onions, thinly sliced", "quantity": "2"}, {"name": "cloves garlic, thinly sliced", "quantity": "4"}, {"name": "courgettes, thinly sliced into rounds", "quantity": "2"}, {"name": "basmati rice, well rinsed", "quantity": "300", "unit": "g"}, {"name": "hot vegetable stock", "quantity": "400", "unit": "ml"}, {"name": "can chickpeas, drained", "quantity": "400", "unit": "g"}, {"name": "pack cherry vine tomatoes, halved", "quantity": "400", "unit": "g"}, {"name": "pack mint, most leaves finely chopped", "quantity": "25", "unit": "g"}, {"name": "heaped tbsp Greek style yogurt", "quantity": "4"}]}]', '["Add 2 tbsp oil to a large deep saucepan over a medium heat. When hot, add the onions and garlic and cook for 5 minutes until softened.", "Tip in the courgettes and cook for 5 minutes more, stirring occasionally. Add the rice, season generously and stir over the heat for 2 minutes.", "Pour in the hot stock with the chickpeas and half the tomatoes, stir briefly, then bring to a simmer for 1 minute. Turn the heat down to low, cover with a clean tea towel and the pan lid and cook for 15 minutes more. Turn off the heat and leave to stand for 10 minutes.", "Meanwhile, finely chop the remaining tomatoes, and dress with the remaining oil. Mix the chopped mint and yogurt in a bowl, then season both to taste.", "Fluff up the rice with 2 forks and pile onto serving plates. Top with the tomato salad, minty yogurt and remaining mint to garnish."]', '["Vegetarian", "Pilaf", "Healthy"]');

-- Recipe 104: Melon & Thai basil rice salad
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(104, 'Melon & Thai basil rice salad', '[{"section_title": "Main", "items": [{"name": "pouches Coconut & Lime Leaf Wholegrain Rice", "quantity": "2x250", "unit": "g"}, {"name": "unwaxed limes, halved", "quantity": "2"}, {"name": "soy & gochujang marinade (see recipe 105)", "quantity": "1", "unit": "quantity"}, {"name": "light olive oil", "quantity": "1", "unit": "tbsp"}, {"name": "pack cherry vine tomatoes, halved", "quantity": "400", "unit": "g"}, {"name": "cantaloupe melon", "quantity": "0.5"}, {"name": "pack Thai basil, leaves torn", "quantity": "0.5x25", "unit": "g"}, {"name": "pack coriander, leaves roughly chopped", "quantity": "25", "unit": "g"}, {"name": "roasted salted cashews, roughly chopped", "quantity": "75", "unit": "g"}, {"name": "Cooks'' Ingredients Crispy Fried Onions", "quantity": "2", "unit": "tbsp", "notes": "optional"}]}]', '["Heat the rice according to pack instructions, then put in a large bowl; set aside to cool.", "Meanwhile, if the barbecue is hot, char the halved limes, cut-side down, for 2-3 minutes (you can also do this in a griddle pan); set aside.", "Put the soy marinade in a jug and whisk in the olive oil.", "Add the tomatoes to the cooled rice with the melon, Thai basil, coriander and half of the cashews.", "When ready to serve, toss through the soy dressing, then arrange on a serving platter. Top with the remaining cashews and the crispy fried onions, if using. Scatter over extra Thai basil and coriander leaves, then serve with the charred limes to squeeze over."]', '["Salad", "Vegan", "Healthy"]');

-- Recipe 105: Soy & Gochujang Marinade
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(105, 'Soy & Gochujang Marinade', '[{"section_title": "Main", "items": [{"name": "caster sugar", "quantity": "1.5", "unit": "tbsp"}, {"name": "soy sauce", "quantity": "2", "unit": "tbsp"}, {"name": "gochujang", "quantity": "1.5", "unit": "tbsp"}, {"name": "toasted sesame oil", "quantity": "1", "unit": "tbsp"}, {"name": "Japanese rice vinegar", "quantity": "3", "unit": "tbsp"}, {"name": "cloves garlic, crushed", "quantity": "2"}, {"name": "chilli flakes", "quantity": "0.5", "unit": "tsp"}]}]', '["In a large bowl, whisk together caster sugar, soy sauce, gochujang, toasted sesame oil, Japanese rice vinegar, crushed garlic, and chilli flakes until well combined.", "Store in the fridge for up to 3 days.", "To make a salad dressing: Whisk in 1 tbsp light olive oil.", "To make a sauce: Whisk into 4 tbsp mayonnaise."]', '["Marinade", "Sauce", "Dressing"]');

-- Recipe 106: Chopped mango salad with crispy chickpeas
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(106, 'Chopped mango salad with crispy chickpeas', '[{"section_title": "Main", "items": [{"name": "cooked chickpeas", "quantity": "250", "unit": "g"}, {"name": "Olive oil", "quantity": "3", "unit": "tbsp"}, {"name": "mild curry powder", "quantity": "2", "unit": "tsp"}, {"name": "small red onion, peeled and finely diced", "quantity": "1"}, {"name": "lemon, juice of", "quantity": "1"}, {"name": "cucumber", "quantity": "0.5"}, {"name": "ripe mangoes, peeled and pitted", "quantity": "2"}, {"name": "amchoor (mango powder), or sumac", "quantity": "1", "unit": "tsp"}, {"name": "ground cumin", "quantity": "1", "unit": "tsp"}, {"name": "red chilli, finely diced", "quantity": "1"}, {"name": "fresh mint leaves, roughly chopped", "quantity": "1", "unit": "handful"}, {"name": "fresh coriander leaves, roughly chopped", "quantity": "1", "unit": "handful"}, {"name": "Sea salt and black pepper", "quantity": "to taste"}]}]', '["Heat the oven to 200°C (180°C fan)/gas 6. Tip the chickpeas into a bowl and rub dry with kitchen paper, removing some of the skins as you do so.", "Transfer the chickpeas to a lined baking tray with three tablespoons of oil, the curry powder and a generous pinch of salt, then toss to coat and bake for 12 minutes, until golden and starting to crisp up.", "Meanwhile, put the onion in a bowl with the lemon juice. Roughly chop the cucumber and mango into 1-2cm chunks, add them to the bowl with a teaspoon of sea salt, the mango powder (or sumac), cumin and chilli, and stir to combine.", "Adjust the seasoning to taste, if need be.", "Once the chickpeas have cooled slightly, add them to the salad bowl with the chopped herbs and another good glug of olive oil, then taste again and adjust as required."]', '["Salad", "Vegetarian", "Healthy"]');

-- Recipe 107: Roast potatoes with peppers and garlic
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(107, 'Roast potatoes with peppers and garlic', '[{"section_title": "Main", "items": [{"name": "baby potatoes, cut in half lengthways", "quantity": "1", "unit": "kg"}, {"name": "thyme", "quantity": "10", "unit": "g"}, {"name": "garlic cloves, skin on", "quantity": "9"}, {"name": "olive oil", "quantity": "120", "unit": "ml"}, {"name": "whole Piccerella peppers, or 2-3 bell peppers, cut in 3cm strips", "quantity": "440", "unit": "g"}, {"name": "Flaked sea salt and black pepper", "quantity": "to taste"}]}]', '["Place the potatoes with half of the thyme and three garlic cloves in a saucepan and cover with plenty of well salted water. Bring to the boil on a high heat, then reduce to medium-high, and cook for five minutes until a knife goes through them easily, then drain.", "Preheat the oven to 180°C (160°C fan)/325°F/gas 4.", "Add the potatoes with all of the garlic (both boiled and raw), thyme and oil to a large tray with a good grind of black pepper. Mix well to coat and place in the oven for 30 minutes, until golden with dark patches in places.", "Increase the heat to 220°C (200°C fan)/425°F/gas 7, stir in the peppers with half a teaspoon of salt, mix and roast for 10-15 minutes until the peppers have blistered and softened.", "Remove from the oven and serve hot."]', '["Side Dish", "Vegetarian", "Roast"]');

-- Recipe 108: Caesar salad with crispy chicken
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(108, 'Caesar salad with crispy chicken', '[{"section_title": "Main", "items": [{"name": "crispy chicken thighs, sliced", "quantity": "4", "notes": "Leftovers"}, {"name": "light mayonnaise", "quantity": "125", "unit": "ml"}, {"name": "lemon, juiced", "quantity": "1"}, {"name": "Worcestershire sauce", "quantity": "1", "unit": "tbsp"}, {"name": "parmesan, grated", "quantity": "50", "unit": "g"}, {"name": "garlic clove, crushed", "quantity": "1"}, {"name": "croûtons", "quantity": "50", "unit": "g"}, {"name": "large Cos lettuce or 4 Little Gem, ripped into pieces", "quantity": "1"}]}]', '["In a large bowl, mix the mayonnaise, lemon juice, Worcestershire sauce, grated parmesan and garlic, then season.", "When ready to eat, add the chicken slices, croutons and lettuce.", "Mix well and sprinkle with extra parmesan, if you like."]', '["Salad", "Chicken", "Quick & Easy"]');

-- Recipe 109: Melon, cucumber and Parma ham salad with basil vinaigrette
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(109, 'Melon, cucumber and Parma ham salad', '[{"section_title": "Main", "items": [{"name": "pack basil, roughly chopped", "quantity": "25", "unit": "g"}, {"name": "extra virgin olive oil", "quantity": "3", "unit": "tbsp"}, {"name": "red wine vinegar", "quantity": "1", "unit": "tbsp"}, {"name": "small cantaloupe melon", "quantity": "1"}, {"name": "cucumber", "quantity": "1"}, {"name": "pack Parma ham", "quantity": "83", "unit": "g"}, {"name": "pecorino, finely sliced", "quantity": "30", "unit": "g"}]}]', '["Whizz the basil, oil and vinegar in a small food processor, season and set aside.", "Halve the melon, scoop out the seeds and discard; slice into wedges then cut away the skin.", "Peel the cucumber, halve lengthways, scoop out the seeds with a teaspoon and discard, then cut into chunky pieces.", "Layer up the salad with the ham and cheese on a serving plate, splashing the vinaigrette in between."]', '["Salad"]');

-- Recipe 110: New potato, tomato and boiled egg salad
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(110, 'New potato, tomato and boiled egg salad', '[{"section_title": "Main", "items": [{"name": "new potatoes", "quantity": "400", "unit": "g"}, {"name": "large eggs, at room temperature", "quantity": "4"}, {"name": "cherry tomatoes, halved", "quantity": "250", "unit": "g"}, {"name": "chives", "quantity": "a good handful"}, {"name": "rapeseed or olive oil", "quantity": "6", "unit": "tbsp"}, {"name": "cider vinegar", "quantity": "4", "unit": "tsp"}, {"name": "English mustard", "quantity": "1", "unit": "tsp"}, {"name": "sugar", "quantity": "a pinch"}, {"name": "Sea salt and freshly ground black pepper", "quantity": "to taste"}]}]', '["Cut the potatoes into chunks if they are large. Put in a pan, cover with water, add salt and bring to the boil. Turn down the heat and simmer for 8-12 minutes, or until tender. Drain well and leave to cool.", "To cook the eggs, bring a pan of water to the boil. Add the eggs, return to a simmer, then cook for 7 minutes. Lightly crack the shells of the eggs and run them under cold water for a minute or two to stop the cooking. Leave until cool, then peel the eggs.", "For the vinaigrette, put the ingredients into a screw-topped jar with some salt and pepper and shake until emulsified.", "Chop the boiled eggs very roughly and put them into a large bowl. Pour on the vinaigrette and mix well, breaking the eggs down a bit as you go.", "Add the potatoes and cherry tomatoes, and toss together. Taste and adjust the seasoning if you need to, then snip over the chives and serve."]', '["Salad", "Vegetarian"]');

-- Recipe 111: Mexican bean salad
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(111, 'Mexican bean salad', '[{"section_title": "Main", "items": [{"name": "eggs", "quantity": "4"}, {"name": "avocados, peeled and stoned", "quantity": "2"}, {"name": "cans of beans (pinto and kidney), rinsed and drained", "quantity": "2x400", "unit": "g"}, {"name": "small red onion, finely sliced", "quantity": "1"}, {"name": "large bunch coriander, leaves only, roughly chopped", "quantity": "1"}, {"name": "cherry tomatoes, halved", "quantity": "250", "unit": "g"}, {"name": "good-quality dressing (e.g. Lime & Coriander)", "quantity": "1", "unit": "bottle"}, {"name": "red chilli, deseeded and finely sliced", "quantity": "1"}, {"name": "cumin", "quantity": "0.5", "unit": "tsp"}]}]', '["Lower the eggs into boiling water and boil for 6.5 mins, then put into a bowl of cold water to cool.", "Slice the avocados and place in a large bowl with the beans, onion, coriander and tomatoes.", "Measure 3 tbsp of the dressing into a small bowl, then mix in the chilli and cumin.", "Once the eggs have cooled but are still warm, peel off the shells and cut into quarters.", "Toss the salad with the dressing and nestle in the eggs. Serve straight away."]', '["Salad", "Vegetarian"]');

-- Recipe 112: Couscous salad with peppers and feta
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(112, 'Couscous salad with peppers and feta', '[{"section_title": "Main", "items": [{"name": "couscous", "quantity": "250", "unit": "g"}, {"name": "olive oil", "quantity": "2", "unit": "tbsp"}, {"name": "lemon, juice of", "quantity": "0.5"}, {"name": "jar chargrilled red peppers in olive oil, drained and diced", "quantity": "280", "unit": "g"}, {"name": "small cucumber, diced", "quantity": "0.5"}, {"name": "small red onion, finely chopped", "quantity": "1"}, {"name": "feta cheese, cubed", "quantity": "200", "unit": "g"}, {"name": "large handful of flat-leaf parsley, finely chopped", "quantity": "1"}, {"name": "Sea salt and freshly ground black pepper", "quantity": "to taste"}]}]', '["Cook the couscous according to the instructions on the packet. As soon as it''s cooked, trickle over the olive oil and lemon juice, season with salt and pepper, and fork the couscous gently to separate the grains. Leave to cool a little, and fork again.", "While the dressed couscous is still just warm, or cool (but not hot), add the red peppers, cucumber, onion, feta and parsley and toss gently until thoroughly combined. Taste and add more salt and pepper if it needs it, and trickle over a little more olive oil if it tastes at all dry. Serve still slightly warm, or at room temperature."]', '["Salad", "Couscous", "Vegetarian"]');

-- Recipe 113: Greek salad
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(113, 'Greek salad', '[{"section_title": "Main", "items": [{"name": "large vine tomatoes, cut into irregular wedges", "quantity": "4"}, {"name": "cucumber, peeled, deseeded, then roughly chopped", "quantity": "1"}, {"name": "red onion, thinly sliced", "quantity": "0.5"}, {"name": "Kalamata olives", "quantity": "16"}, {"name": "dried oregano", "quantity": "1", "unit": "tsp"}, {"name": "feta cheese, cut into chunks", "quantity": "85", "unit": "g"}, {"name": "Greek extra virgin olive oil", "quantity": "4", "unit": "tbsp"}]}]', '["Place all ingredients in a large bowl.", "Lightly season, then serve with crusty bread to mop up all of the juices."]', '["Salad", "Vegetarian", "Quick & Easy"]');

-- Recipe 114: Speedy Tuna Nicoise Salad
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(114, 'Speedy Tuna Nicoise Salad', '[{"section_title": "Main", "items": [{"name": "baby new potatoes, halved", "quantity": "300", "unit": "g"}, {"name": "green beans, trimmed", "quantity": "200", "unit": "g"}, {"name": "tomatoes, quartered", "quantity": "2"}, {"name": "hard-boiled eggs, quartered", "quantity": "2"}, {"name": "can John West No Drain Tuna Steak with Brine", "quantity": "130", "unit": "g"}, {"name": "spinach leaves", "quantity": "50", "unit": "g"}, {"name": "pitted black olives", "quantity": "10"}, {"name": "lemon juice", "quantity": "1", "unit": "tbsp"}, {"name": "extra virgin olive oil", "quantity": "1", "unit": "tbsp"}]}]', '["Boil the potatoes for 5-10 minutes, until almost tender. Add the green beans and cook for a further 3-5 minutes, or until the potatoes and beans are tender. Drain and rinse under cold water. Set aside.", "Combine the tomatoes, eggs, tuna, spinach, olives, potatoes and green beans.", "Mix together the lemon juice and olive oil; season and drizzle over the salad. Spoon onto 2 plates and serve immediately."]', '["Salad", "Tuna", "Quick & Easy"]');

-- Recipe 115: Crispy black bean burgers
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(115, 'Crispy black bean burgers', '[{"section_title": "Main", "items": [{"name": "Olive oil", "quantity": "3", "unit": "tbsp"}, {"name": "large onions, peeled and thinly sliced", "quantity": "2"}, {"name": "salt", "quantity": "1", "unit": "tsp"}, {"name": "tin black beans, not drained", "quantity": "400", "unit": "g"}, {"name": "dried breadcrumbs", "quantity": "80", "unit": "g"}, {"name": "dried garlic granules", "quantity": "1", "unit": "tsp"}, {"name": "dried onion granules", "quantity": "1", "unit": "tsp"}, {"name": "chipotle paste", "quantity": "1", "unit": "tbsp"}, {"name": "dijon mustard", "quantity": "2", "unit": "tsp"}, {"name": "tomato ketchup", "quantity": "1", "unit": "tbsp"}]}, {"section_title": "To serve", "items": [{"name": "burger buns", "quantity": "4"}, {"name": "Vegan mayonnaise"}, {"name": "Iceberg lettuce"}, {"name": "Finely sliced tomato"}]}]', '["Put three tablespoons of olive oil in a medium frying pan set over a medium heat and, once it''s hot, add the onion and a half-teaspoon of salt, and cook, stirring often, for 20 minutes, until quite reduced and frazzled. Take off the heat.", "Meanwhile, spoon a couple of tablespoons of the liquid (aquafaba) from the tin of beans into a small bowl or mug and set aside. Drain and rinse the beans, tip into a large bowl and roughly mash; leave a few whole or in big chunks.", "Stir in the breadcrumbs, garlic granules, onion granules, chipotle paste, mustard, ketchup and a half-teaspoon of salt, then use your hands to mix until well combined; if need be, add some or all of the reserved aquafaba.", "Divide the bean mix evenly into four, roll each piece into a ball, then put them one by one between two sheets of baking paper and press out to roughly 10cm- to 12cm-wide patties.", "To cook the patties, put two tablespoons of olive oil in a medium frying pan, then fry two of the burgers for about six minutes in total, turning them once halfway, or when the base is crisp and golden. Remove and set aside, add another two tablespoons of oil, then repeat with the other two patties.", "To serve, split and toast the buns, spread a generous dollop of mayo over the cut side of the bases and top with a leaf or two of iceberg lettuce. Add a bean patty and a couple of thin slices of tomato, and finish with a quarter of the caramelised onions. On with the lids and eat immediately."]', '["Burger", "Vegetarian", "Vegan"]');

-- Recipe 116: Buttery tomato chickpeas & orecchiette
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(116, 'Buttery tomato chickpeas & orecchiette', '[{"section_title": "Main", "items": [{"name": "butter", "quantity": "50", "unit": "g"}, {"name": "onion, diced", "quantity": "1"}, {"name": "large bay leaf", "quantity": "1"}, {"name": "clove garlic, thinly sliced", "quantity": "1"}, {"name": "small pinch saffron", "quantity": "1"}, {"name": "cans plum tomatoes", "quantity": "2x400", "unit": "g"}, {"name": "jar Bold Bean Co Queen Chick Peas", "quantity": "700", "unit": "g"}, {"name": "No.1 Orecchiette", "quantity": "150", "unit": "g"}, {"name": "Parmigiano Reggiano, finely grated, to serve", "quantity": "to taste"}, {"name": "Extra virgin olive oil, to serve", "quantity": "optional"}]}]', '["Melt the butter in a large saucepan, then add the onion and bay leaf and fry gently with the lid on for 10-15 minutes, stirring occasionally, until the onion is softened.", "Stir in the garlic and saffron and cook for 3-4 minutes more. Tip in the tomatoes with the chickpeas and the liquid from the jar. Season and simmer for 20 minutes, roughly breaking up the tomatoes.", "Stir in the pasta with 400ml boiling water (or stock). Bring to a boil, then allow to simmer gently for 16-18 minutes more, until the pasta is tender and the sauce is soupy.", "Sprinkle over the parmesan, then serve in shallow bowls, with a drizzle of extra virgin olive oil, if liked."]', '["Pasta", "Vegetarian"]');

-- Recipe 117: Rice and peas with mint and sesame oil
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(117, 'Rice and peas with mint and sesame oil', '[{"section_title": "Main", "items": [{"name": "white miso paste", "quantity": "3", "unit": "tbsp"}, {"name": "Rapeseed oil", "quantity": "4", "unit": "tbsp"}, {"name": "spring onions, trimmed and finely sliced", "quantity": "200", "unit": "g"}, {"name": "fine sea salt", "quantity": "1", "unit": "tsp"}, {"name": "arborio risotto rice", "quantity": "250", "unit": "g"}, {"name": "root ginger, peeled and grated", "quantity": "5cm x 2cm piece"}, {"name": "frozen petit pois, defrosted", "quantity": "200", "unit": "g"}, {"name": "white pepper", "quantity": "1.5", "unit": "tsp"}, {"name": "fresh mint, leaves picked and finely chopped", "quantity": "40", "unit": "g"}, {"name": "rice vinegar", "quantity": "2", "unit": "tbsp"}, {"name": "toasted sesame oil", "quantity": "3", "unit": "tbsp"}]}]', '["First make a stock. Put the miso in a large jug, pour over a litre and a half of just-boiled water, stir and put to one side.", "Put four tablespoons of oil in a casserole pot on a medium heat and, once it''s hot, add the sliced spring onions and salt, and cook, stirring, for three or four minutes, until softened.", "Add the rice and ginger, stir to coat the rice in the oil, then pour in the miso stock and bring to a simmer.", "Turn down the heat and leave to cook, stirring occasionally, for 25 minutes. Add the peas, cook for a further five minutes, then stir in the white pepper. The rice should be starchy but creamy, soft and almost soupy.", "While the rice is cooking, make the mint and sesame oil. Put the mint, rice vinegar, toasted sesame oil and a tablespoon of rapeseed oil in a small bowl and stir to combine.", "Distribute the rice between bowls, spoon some of the mint and sesame oil over the top, and serve."]', '["Rice", "Vegetarian", "Vegan"]');

-- Recipe 118: Tuna melt, my way
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(118, 'Tuna melt, my way', '[{"section_title": "Main", "items": [{"name": "olive oil", "quantity": "1", "unit": "tsp"}, {"name": "spring onions, trimmed and thinly sliced", "quantity": "2-3"}, {"name": "tin tuna in brine, drained", "quantity": "1x145", "unit": "g"}, {"name": "mature cheddar, grated", "quantity": "50", "unit": "g"}, {"name": "thick slice of sourdough, lightly toasted", "quantity": "1"}, {"name": "crisp fried onions", "quantity": "1-2", "unit": "tbsp"}]}]', '["Warm the oil in a small frying pan on a medium-high heat, then add the spring onions and fry, stirring, for two to three minutes, until nicely softened.", "Stir in the tuna, turn up the heat to high and fry for 30 seconds.", "Scatter in the cheese, stir to combine until it melts, then tip the lot over the toasted sourdough, top with crisp onions and tuck in."]', '["Sandwich", "Tuna", "Quick & Easy"]');

-- Recipe 119: Easy, cheesy toastie
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(119, 'Easy, cheesy toastie', '[{"section_title": "Main", "items": [{"name": "grated double gloucester", "quantity": "1", "unit": "big handful"}, {"name": "egg", "quantity": "1"}, {"name": "Worcestershire sauce", "quantity": "to taste"}, {"name": "ploughman''s chutney, or another fruity chutney", "quantity": "1", "unit": "tbsp"}, {"name": "Salted butter"}, {"name": "slices white bread", "quantity": "2"}]}]', '["Put the cheese, egg, a generous splash of Worcestershire sauce and plenty of chutney in a small bowl and mix to a paste.", "Butter one side of each slice of bread, slather the filling on the unbuttered side of one slice of bread and top with the second slice of bread buttered side up.", "Melt a knob of butter in a frying pan on a low heat, then gently fry the sandwich for three or four minutes on each side, until the cheese melts, the egg binds the filling together and the bread is nicely toasted, then cut in half and tuck in."]', '["Sandwich", "Vegetarian", "Quick & Easy"]');

-- Recipe 120: Middle Eastern Rice (Mejadra)
INSERT INTO recipes (id, name, ingredients, instructions, tags) VALUES
(120, 'Middle Eastern Rice (Mejadra)', '[{"section_title": "Rice", "items": [{"name": "olive oil", "quantity": "2", "unit": "tbsp"}, {"name": "cumin seeds (or 1 tsp ground cumin)", "quantity": "2", "unit": "tsp"}, {"name": "coriander seeds (or 1.5 tsp ground coriander)", "quantity": "1.5", "unit": "tbsp"}, {"name": "basmati or long grain rice, uncooked", "quantity": "1", "unit": "cup"}, {"name": "water", "quantity": "1.25", "unit": "cup"}, {"name": "canned brown lentils, drained", "quantity": "400", "unit": "g"}, {"name": "ground turmeric", "quantity": "0.5", "unit": "tsp"}, {"name": "ground cinnamon", "quantity": "1.5", "unit": "tsp"}, {"name": "sugar", "quantity": "1", "unit": "tsp"}, {"name": "salt", "quantity": "1", "unit": "tsp"}, {"name": "Black pepper", "quantity": "to taste"}]}, {"section_title": "Crispy Fried Onions", "items": [{"name": "large onions, very finely sliced", "quantity": "3"}, {"name": "vegetable or sunflower oil", "quantity": "1", "unit": "cup"}, {"name": "Salt", "quantity": "to taste"}]}]', '["Crispy Onions: Heat oil in a medium saucepan over medium high heat. Add about 1/3 of the onions and cook for 5 minutes until golden and crispy. Drain on paper towels. Repeat with remaining onions, in two batches.", "Rice: Put the olive oil, cumin seeds and coriander in a saucepan over medium heat. Cook for a couple of minutes until the spices are fragrant.", "Add the rice and stir to coat with the oil and spices.", "Add the water and lentils.", "While it comes to boil, add all the other spices, salt and pepper.", "When it comes to a boil, turn it down to medium-low, cover with lid and let cook for 10 to 12 minutes, or until all the liquid has mostly been absorbed.", "Remove from heat and let it rest for 10 minutes - during this time, any residual liquid will absorb.", "Fluff rice with a fork and adjust the seasoning with more salt if you wish.", "Just prior to serving, stir through most of the onions and top with remainder. Sprinkle with chopped coriander if desired. Best served warm."]', '["Rice", "Pilaf", "Vegetarian", "Vegan"]');
