
name = "home-recipes-app-github"
compatibility_date = "2023-10-30"

# This section is crucial for Cloudflare Pages to correctly build your functions.
# It tells the build system where to find the static assets (your public directory)
# and instructs it to build any functions it finds.
[pages_build_config]
build_output_dir = "public"
build_command = ""

# D1 database binding for your production environment.
[[d1_databases]]
binding = "DB"
database_name = "recipes-db"
database_id = "45c9bc04-bafb-4ea7-9926-9de33ac06e32"

