name = "home-recipes-app-github"
main = "src/index.ts" # Tells `wrangler dev` where your API code is
compatibility_date = "2023-10-30"

# Tells `wrangler dev` where your static HTML/JS files are
[site]
bucket = "./public"

# Your existing D1 database binding - no changes needed here
[[d1_databases]]
binding = "DB"
database_name = "recipes-db"
database_id = "45c9bc04-bafb-4ea7-9926-9de33ac06e32"